#Elastic Logs
#logging.level.org.springframework.data.elasticsearch.core=DEBUG
#logging.level.tracer=TRACE

#Elastic conf
elastic:
  scheme: https
  host: iadata-internal-proxy
  port: 1443
  useSSL: true
  securityType: apiKey
  technicalApiKeyBase64: TVg2NkNuUUIwMVVlb2M5bXUwbl86Ujl2aTZjeHlSX3kzY1AwcHgwTDN5Zw==
  commonPassword: K?C!HwY'^!*!(j3P
  visitorApiKeyBase64: NHptYVEzUUIwMVVlb2M5bXFZYm86YmtfZDRzOXNUTjJyUkV2c1BMamFLZw==

siteback:
  api:
    userid:
      transform: LOWERCASE

spring:
  datasource:
    url: jdbc:mysql://iadata.applis.toulouse-metropole.fr:1600/iadata-config
    password: dWQNrwQhXDefFR73LNAGQpza
    initialization-mode: never


microservice:
  daemon: tcp://iadata.toulouse-metropole.fr:2375


# apifetcher properties
apiConsume:
  customHeaders:
    Bearer: TVg2NkNuUUIwMVVlb2M5bXUwbl86Ujl2aTZjeHlSX3kzY1AwcHgwTDN5Zw==
paginaterangeprovider:
  valueStart: 0
ingest:
  ingestMode: api
  urlApiIngest: "https://iadata-ingest.applis.toulouse-metropole.fr/v2/"
  tokenApiIngest: "TVg2NkNuUUIwMVVlb2M5bXUwbl86Ujl2aTZjeHlSX3kzY1AwcHgwTDN5Zw=="
