# disable embedded tomcat
spring:
  main:
    web-environment: false

# Choose the updateDelay on the HTTP call (default : every minute )
dataFetcher:
  pollingCronExpression: ${POLLING_CRON_EXPRESSION:0 * * * * ?}

# consume api properties
apiConsume:
  urlApiConsume: ${URL_API_CONSUME}
  loginApiConsume: ${LOGIN_API_CONSUME} # when securityTypeApiConsume = basic
  passwordApiConsume: ${PASSWORD_API_CONSUME} # when securityTypeApiConsume = basic
  tokenApiConsume: ${TOKEN_API_CONSUME}
  securityTypeApiConsume: ${SECURITY_TYPE_API_CONSUME} # may be basic, bearer or none

# sending to ingest pipeline properties
ingest:
  ingestMode: tcp
  ingestTopic: ${INGEST_TOPIC}
  urlApiIngest: localhost:8082
  brokerIngestHost: localhost
  brokerIngestPort: 9092


management:
  endpoints:
    web:
      exposure:
        include: refresh