  
server:
  port: 8098
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/font-woff2,application/octet-stream
    min-response-size: 1024
spring:
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchReactiveHealthContributorAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration
  security:
    user:
      name: log
      password: pass
  data:
    rest:
      basePath: /api/models

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://iadata-internal-proxy:1447/iadata-config
    username: tm-iadata-sql
    password: # to set depending on environment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: refresh


#Elastic conf
elastic:
  scheme: http
  host: localhost
  port: 9200
  useSSL: false
  securityType: none
  username: elastic
  pass: pwdElastic@2020
  technicalApiKeyBase64:
  userPrefix: ta_
  commonPassword:
  visitorUserId: visitor
  visitorApiKeyBase64:

microservice:
  daemon:
  registry: iadata-mgr.applis.intra:5000
  network: swarm-iadata_dmz

pipeline:
  maxDumpsNumber: 3


siteback:
  outputDir: /iadata_outbox/
  api:
    userid:
      transform: NONE
  admin:
    role:
      name: role_user_dn
  superuser:
    role:
      name: superuser

streamsapi:
  baseUri: http://iadata-internal-proxy:1445/api/
  pathStart: start
  pathStop: stop
  pathRestart: restart

  # Choose the updateDelay on the HTTP call (default : every minute )
dataFetcher:
  pollingCronExpression: '-'
  prepareDataServiceMode: jsonArrayPropertyGetterSplitter
  propertyToExtract: originalRawData
  scheduleMode: none
  fetchMode: custom
  behindProxy: false
  proxyHostEnvName: PROXY_HOST
  proxyPortEnvName: PROXY_PORT
  proxyUserNameEnvName: PROXY_USERNAME
  proxyPasswordEnvName: PROXY_PASSWORD
  recoverObjectStartDir: /datafetcher_config/

  # apifetcher properties
  apiConsume:
    loginRawData:
    urlLogin:
    cookieLoginName:
    urlApiConsume:
    loginApiConsume:
    passwordApiConsume:
    securityTypeApiConsume: none
    method: get
    customHeaders:
      Content-Type: 'application/json'
      Bearer: QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ==
    body: ''
    responseType: json
    jsonPathData: "$['content']"
  paginaterangeprovider:
    valueStart: 0
  ingest:
    ingestMode: api
    urlApiIngest: "https://iadata-dev-ingest.applis.intra/v2/"
    tokenApiIngest: "QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ=="
    ingestTopic:


