spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
---
api:
  data:
    url: "http://iadata-internal-proxy:1444/api/models"
    securityHeaderName: ApiKey
    securityHeaderValue: "V2s3bEVIZ0IxRXBVWnBVN1RScGU6SUd2N1JhN09ScnF2ZlRDeW9IaUx5QQ=="

---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: IGv7Ra7ORrqvfTCyoHiLyA 
  apiid: Wk7lEHgB1EpUZpU7TRpe
  host: iadata-internal-proxy
  port: 1443
---
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
    tracer: TRACE

