#Elastic Logs
#logging:
#  level:
    #org.springframework.data.elasticsearch.core: DEBUG
    #tracer: TRACE
#    fr.toulouse.iadata: DEBUG

#Elastic conf
elastic:
  scheme: https
  host: iadata-internal-proxy
  port: 1443
  useSSL: true
  securityType: apiKey
  technicalApiKeyBase64: QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ==
  commonPassword: 97@Z&$Nmy(HX.QU~
  visitorApiKeyBase64: bXI0dUJuUUJrNmo1dk50bmh3OTc6ME5LYVE4dVJUUHFjVGVnV19ZejJFZw==

spring:
  datasource:
    url: jdbc:mysql://iadata-dev.applis.intra:10446/iadata-config
    password: SVZsaUjMd4mMx4wrFB8cM8z3

siteback:
  api:
    userid:
      transform: LOWERCASE

microservice:
  daemon: tcp://iadata-dev.applis.intra:2375
# apifetcher properties
apiConsume:
  customHeaders:
    Bearer: QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ==
paginaterangeprovider:
  valueStart: 0
ingest:
  ingestMode: api
  urlApiIngest: "https://iadata-dev-ingest.applis.intra/v2/"
  tokenApiIngest: "QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ=="