# disable embedded tomcat
spring:
  main:
    web-environment: false

# Choose the updateDelay on the HTTP call (default : every minute )
dataFetcher:
  pollingCronExpression: '0 * * * * *' # "-" to disable the scheduling
  scheduleMode: scheduled # none, only_once, scheduled
  fetchMode: range
  prepareDataServiceMode: jsonArraySplitter
  behindProxy: true
  proxyHostEnvName: PROXY_HOST
  proxyPortEnvName: PROXY_PORT
  proxyUserNameEnvName: PROXY_USERNAME
  proxyPasswordEnvName: PROXY_PASSWORD
  recoverObjectStartPath: /datafetcher_config/iadata-datafetcher-logitud-control-recover.config

# apifetcher properties
apiConsume:
  loginRawData: "{\"username\":\"statistique\",\"password\":\"*Stat!68\"}"
  urlLogin: https://services.logitud.fr/toulouse-asvp/auth-server/login/
  cookieLoginName: sid
  urlApiConsume: https://services.logitud.fr/toulouse-asvp/security/activity/activities
  loginApiConsume:
  passwordApiConsume:
  securityTypeApiConsume: json
  method: post
  customHeaders:
    Content-Type : application/json
    uuid : 8950A6F5-A792-4AD4-880D-005809356708
  body: '{"context":"gvs.control","dateFrom":"@@@from@@@","dateTo":"@@@to@@@"}'
  responseType: json
  jsonPathData: "$['matches']"

daterangeprovider:
  valueStart: 2020-07-01T00:00:00
  format: "yyyy-MM-dd'T'HH:mm:ss"