# dont run job on startup
spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  main:
    web-application-type: none
  # Kafka config
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Files dir
app:
  scheduling:
    enable: true

fileprocessor:
  inbox : /iadata_inbox
  readyToIngestExtension: "readyToIngest"
  processingExtension: "processing"
  processedExtension: "processed"
  cronFileProcessorDirWatcher: "*/5 * * ? * ? *"

