spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
---
apidata:
  url: "https://iadata-dev.applis.intra:10444/api/v1/entities/"
  securityHeaderName: ApiKey
  securityHeaderValue: "QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ=="
---
apimodels:
  url: "https://iadata-dev.applis.intra:10444/api/models/"
  securityHeaderName: ApiKey
  securityHeaderValue: "QkszUHIzUUJXX1c3RTNWYWIxNkM6N2ZJanhjUDlURE9PLS1UWEZab25MUQ=="
---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: 4FcG9fl_Tq6o_dToeTp3fw
  apiid: yEwknnIBe_6zRi5OnEdV
  host: iadata-dev-ingest.applis.intra
  port: 10443
