spring:
  kafka:
    client-id: notify-sms
    bootstrap-servers:
      - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
etoilediese:
  urlSendSms: https://ssl.etoilediese.fr/envoi/sms/envoi.php
  usernameQueryParam: u
  passwordQueryParam: p
  dateForMD5QueryParam: date
  textQueryParam: t
  phoneNumberQueryParam: n
  messageTypeQueryParam: f
  urgenceLevelQueryParam: urg
  sendingDateQueryParam: dte
  categoryQueryParam: c
  authenticationFailedResponseContent: 'Echec : identification incorrecte'
  authenticationMissingResponseContent: 'Echec : veuillez vous identifier'
  textMissingResponseContent: 'Echec : veuillez preciser votre texte'
  endUserAddressMissingResponseContent: 'Echec : veuillez preciser votre correspondant'
  noMoreCreditResponseContent: 'Echec : plus de credit'
  unauthorizedEndUserResponseContent : 'Echec : numero interdit'
  endUserUndeliverableResponseContent : 'Echec: stop'

notifysms:
  behindProxy: true
  proxyHostEnvName: PROXY_HOST
  proxyPortEnvName: PROXY_PORT
  proxyUserNameEnvName: PROXY_USERNAME
  proxyPasswordEnvName: PROXY_PASSWORD
  userNameSMSServiceAuthen: iottoulouse562
  passwordSMSServiceAuthent: VxV84m9ebm
  topicIn: iadata-data-alert-notify-sms
