logging:
  level:
    fr.toulouse.iadata: DEBUG
 
spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
---
apidata:
  url: "http://iadata-internal-proxy:1444/api/v1/entities/"
  securityHeaderName: Authorization
  securityHeaderValue: "ApiKey TVg2NkNuUUIwMVVlb2M5bXUwbl86Ujl2aTZjeHlSX3kzY1AwcHgwTDN5Zw=="
---
apimodels:
  url: "http://iadata-internal-proxy:1444/api/models/"
  securityHeaderName: Authorization
  securityHeaderValue: "ApiKey TVg2NkNuUUIwMVVlb2M5bXUwbl86Ujl2aTZjeHlSX3kzY1AwcHgwTDN5Zw=="
---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: R9vi6cxyR_y3cP0px0L3yg
  apiid: MX66CnQB01Ueoc9mu0n_
  host: iadata-internal-proxy
  port: 1443
