spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
---
api:
  data:
    url: "http://iadata-internal-proxy:1444/api/models"

---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: nj8canYBGqLkLDHHYAHr 
  apiid: TH739wtXSnqR_kI9-_M8Ow
  host: iadata-internal-proxy
  port: 1443
---
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
    tracer: TRACE




