spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
ingest:
  upload:
    dir: #TODO
---
api:
  data:
    url: "http://iadata-internal-proxy:1444/api/models"

---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: T1LGj4MsTWmLeq1-tilKug
  apiid: 9NcZ53IBOJFeiQSKC5PY
  host: iadata-internal-proxy
  port: 1443
---
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
    tracer: TRACE




