spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:10.198.0.91}:${KAFKA_PORT:9094}
ingest:
  upload:
    dir: #TODO
---
api:
  data:
    url: "https://iadata-dev.applis.intra/api/models"
---
elastic:
  useSSL: true
  securityType: apiKey
  username:
  pass:
  apikey: 4FcG9fl_Tq6o_dToeTp3fw
  apiid: yEwknnIBe_6zRi5OnEdV
  host: iadata-dev-ingest.applis.intra
  port: 10443
